CREATE TABLE IF NOT EXISTS `media` (
    `id` BIGINT PRIMARY KEY,
    `CREATION_TIME` DATETIME,
    `MODIFICATION_TIME` DATETIME,
    `URL` VARCHAR(255),
    `FEED` BIGINT,
    `FILE_NAME` VARCHAR(255),
    `MEDIA_TYPE` VARCHAR(50),
    `CUSTOMER_ID` BIGINT,
    `NAME` VARCHAR(255),
    `DESCRIPTION` TEXT,
    `EXTENSION` VARCHAR(50),
    `CREATED_BY` BIGINT
);
