package com.juvarya.nivaas.customer.model.constants;

public enum NotificationType {

	WELCOME, USER, FEED, REEL, PENDING, APPROVED, APARTMENT_APPROVED, WAITING_FOR_APPROVAL, APARTMENT_ONBOARD,
	FLAT_ONBOARD, FLAT_APPROVED, TENANT_ONBOARD, TENANT_APPROVAL, SOCIETY_DUE, FLAT_OWNER_FAMILY_MEMBER
	
}
